import React from "react";
import type { Metadata } from "next";
import { Roboto_Condensed } from "next/font/google";

import { Header } from "@/components/shared/header";
import { Footer } from "@/components/shared/footer";

import "./globals.css";

const robotoCondensed = Roboto_Condensed({
  subsets: ["cyrillic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoCondensed.className} bg-black`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
